/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getAllHelpers(filePath: string): Array<string>
export function extractAllHelpers(files: Array<string>): Array<string>
